---
- name: Run show commands on Cisco IOS devices
  hosts: ciscoIOS
  gather_facts: false
  tasks:
    - name: Run Show Version command
      cisco.ios.ios_command:
        commands:
          - show Version
      register: cisco_ios_ios_command

    - name: Display cisco_ios_ios_command output
      ansible.builtin.debug:
        var: cisco_ios_ios_command

    # - name: show gather facts
    # ansible.builtin.debug:
    #   var: ansible_facts
